#!/usr/bin/env bash
# picopi installer for non-Nix users.
#
#   ./scripts/install.sh [AGENT_DIR]
#
# Installs picopi into a single agent directory (default: ~/.config/picopi) that
# holds everything — picopi resources AND pi's own config/settings/models/auth —
# and creates a `picopi` launcher that points pi at it. Your plain `pi` and
# ~/.pi/agent are left completely untouched.
# Requires pi on PATH (https://github.com/earendil-works/pi) and python3.
# Picopi resources are overwritten; your config/settings/models/auth persist.
set -euo pipefail

repo="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
dir="${1:-${XDG_CONFIG_HOME:-$HOME/.config}/picopi}"
bindir="${PICOPI_BINDIR:-$HOME/.local/bin}"

pi_bin="$(command -v pi || true)"
if [ -z "$pi_bin" ]; then
  echo "error: 'pi' not found on PATH. Install it first:" >&2
  echo "  https://github.com/earendil-works/pi" >&2
  exit 1
fi

echo "Installing picopi into $dir"
mkdir -p "$dir"

# Picopi-owned resources — safe to overwrite on every install.
rm -rf "$dir/src" "$dir/agents" "$dir/prompts" "$dir/themes"
cp -r "$repo/src"            "$dir/src"
cp -r "$repo/agent/agents"   "$dir/agents"
cp -r "$repo/agent/prompts"  "$dir/prompts"
cp -r "$repo/agent/themes"   "$dir/themes"
cp "$repo/agent/AGENTS.md"   "$dir/AGENTS.md"
echo "  installed src/, agents/, prompts/, themes/, AGENTS.md"

# config.json (picopi roles/aliases): seed once, never clobber.
if [ -e "$dir/config.json" ]; then
  echo "  kept    config.json"
else
  cp "$repo/agent/config.json" "$dir/config.json"
  echo "  created config.json"
fi

# settings.json: merge picopi's resource wiring into existing settings without
# clobbering the user's choices.
python3 - "$repo" "$dir" <<'PY'
import json, os, sys
repo, dir = sys.argv[1], sys.argv[2]
base = json.load(open(f"{repo}/agent/settings.json"))
p = f"{dir}/settings.json"
cur = json.load(open(p)) if os.path.exists(p) else {}
merged = {**base, **cur}
ext = cur.get("extensions", [])
merged["extensions"] = list(dict.fromkeys([*(e for e in ext if e != "src"), "src"]))
for k, v in (("prompts", "prompts"), ("themes", "themes")):
    vals = merged.get(k, [])
    merged[k] = list(dict.fromkeys([*(x for x in vals if x != v), v]))
merged.setdefault("theme", "picopi")
json.dump(merged, open(p, "w"), indent=2)
print("  merged  settings.json (resource wiring added; your keys preserved)")
PY

# models.json: empty stub once; it's your data.
[ -e "$dir/models.json" ] || printf '{\n  "providers": {}\n}\n' > "$dir/models.json"

# `picopi` launcher: points pi at our agent dir, leaving the user's plain `pi`
# and ~/.pi/agent untouched. We bake in the resolved pi path and agent dir.
mkdir -p "$bindir"
launcher="$bindir/picopi"
cat > "$launcher" <<LAUNCHER
#!/usr/bin/env bash
# picopi launcher (generated by scripts/install.sh) — runs pi against the picopi
# agent dir without affecting your normal pi setup. Override the dir with \$PICOPI_HOME.
exec env PI_CODING_AGENT_DIR="\${PICOPI_HOME:-$dir}" $(printf '%q' "$pi_bin") "\$@"
LAUNCHER
chmod +x "$launcher"
echo "  created $launcher"

in_path=no
case ":$PATH:" in *":$bindir:"*) in_path=yes ;; esac

cat <<EOF

All your config lives in: $dir/
  config.json    picopi roles/aliases — map pro/flash to models you can use
  models.json    providers/models (see examples/models.example.json)
  settings.json  pi settings

Run it with:  picopi
EOF

if [ "$in_path" = no ]; then
  cat <<EOF

Note: $bindir is not on your PATH. Add it (then restart your shell):
  export PATH="$bindir:\$PATH"
Or run directly: $launcher
EOF
fi

cat <<EOF

Then add a provider/model + key (env vars or 'pi login'; see pi's provider docs).

Uninstall: rm $launcher && rm -rf $dir
EOF
