#!/usr/bin/env bash
# picopi installer for non-Nix users.
#
#   ./scripts/install.sh
#
# Creates a `picopi` launcher that runs pi against a config dir holding ONLY
# your user state (config.json, settings.json, models.json, auth.json,
# sessions/). All picopi source — the extension, prompts, themes, agents,
# AGENTS.md — stays in this repo and is handed to pi via CLI flags; nothing is
# copied into the config dir. Update picopi with a plain `git pull`.
# Your plain `pi` and ~/.pi/agent are left completely untouched.
# Requires pi on PATH (https://github.com/earendil-works/pi).
set -euo pipefail

repo="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
# shellcheck source=scripts/_lib.sh
. "$repo/scripts/_lib.sh"

# ── --help ────────────────────────────────────────────────────────────────────
if [ "${1:-}" = "--help" ] || [ "${1:-}" = "-h" ]; then
  echo -e "$H picopi — opinionated pi setup"
  cat <<EOF

Usage: ./scripts/install.sh [--help]

Creates ~/.local/bin/picopi launcher and seeds config in
~/.config/picopi (override with PICOPI_HOME / PICOPI_BINDIR).

Config files are seeded once and never overwritten.
Your existing pi is not touched.

Note: the launcher bakes in the repo path; if you move the repo, re-run install.
Docs: https://github.com/j4ger/picopi#quickstart
Uninstall: rm ~/.local/bin/picopi && rm -rf ~/.config/picopi
EOF
  exit 0
fi

# ── preflight ─────────────────────────────────────────────────────────────────
dir="${PICOPI_HOME:-${XDG_CONFIG_HOME:-$HOME/.config}/picopi}"
bindir="${PICOPI_BINDIR:-$HOME/.local/bin}"

pi_bin="$(command -v pi || true)"
if [ -z "$pi_bin" ]; then
  fail "'pi' not found on PATH — install it first: https://github.com/earendil-works/pi"
  exit 1
fi

[ -n "${PICOPI_NO_HEADER:-}" ] || echo -e "$H picopi — installing to $dir"
mkdir -p "$dir"

# ── one-time migration off the old "copy source into the config dir" layout ──
if [ -e "$dir/.stamp" ] || [ -d "$dir/src" ]; then
  rm -rf "$dir/.stamp" "$dir/src" "$dir/agents" "$dir/prompts" "$dir/themes" "$dir/AGENTS.md"
  if command -v python3 >/dev/null && [ -e "$dir/settings.json" ]; then
    python3 - "$dir/settings.json" <<'PY'
import json, sys
p = sys.argv[1]
s = json.load(open(p))
for k in ("extensions", "prompts", "themes", "skills"):
    s.pop(k, None)
json.dump(s, open(p, "w"), indent=2)
PY
  fi
  ok "migrated: removed old source copies"
fi

# ── seed user-owned files once; never clobber ─────────────────────────────────
if [ -e "$dir/config.json" ]; then
  ok "config.json (kept)"
else
  cp "$repo/agent/config.json" "$dir/config.json"
  ok "config.json"
fi
if [ -e "$dir/settings.json" ]; then
  ok "settings.json (kept)"
else
  cp "$repo/agent/settings.json" "$dir/settings.json"
  ok "settings.json"
fi
[ -e "$dir/models.json" ] || printf '{\n  "providers": {}\n}\n' > "$dir/models.json"

# ── generate launcher ─────────────────────────────────────────────────────────
# Note: the launcher embeds $repo as an absolute path. If the repo is moved,
# re-run install.sh to regenerate the launcher.
mkdir -p "$bindir"
launcher="$bindir/picopi"
cat > "$launcher" <<LAUNCHER
#!/usr/bin/env bash
# picopi launcher (generated by scripts/install.sh).
repo=$(printf '%q' "$repo")
exec env \\
  PICOPI_SRC="\$repo" \\
  PICOPI_PI_FALLBACK=$(printf '%q' "$pi_bin") \\
  PICOPI_UPDATE_CMD="\$repo/scripts/update.sh" \\
  bash "\$repo/scripts/picopi-launch.sh" "\$@"
LAUNCHER
chmod +x "$launcher"
ok "launcher → $launcher"

# ── PATH hint ─────────────────────────────────────────────────────────────────
in_path=no
case ":$PATH:" in *":$bindir:"*) in_path=yes ;; esac
if [ "$in_path" = no ]; then
  warn "$bindir not on PATH — add it or run $launcher directly"
fi

echo -e "$H done — run ${B}picopi${X} to start"
echo -e "  ${D}Optional:${X} run ${B}npm install${X} (or ${B}bun install${X}, ${B}pnpm install${X}) in the repo for better web HTML-to-text conversion (turndown)"
if ! command -v rtk >/dev/null 2>&1; then
  echo -e "  ${D}Optional:${X} install ${B}rtk${X} (e.g. ${B}brew install rtk${X} or ${B}curl -fsSL https://raw.githubusercontent.com/rtk-ai/rtk/refs/heads/master/install.sh | sh${X}) for token-efficient bash output — picopi auto-detects it at runtime"
fi
