#!/usr/bin/env bash
# picopi installer for non-Nix users.
#
#   ./scripts/install.sh
#
# Creates a `picopi` launcher that runs pi against a config dir holding ONLY
# your user state (config.json, settings.json, models.json, auth.json,
# sessions/). All picopi source — the extension, prompts, themes, agents,
# AGENTS.md — stays in this repo and is handed to pi via CLI flags; nothing is
# copied into the config dir. Update picopi with a plain `git pull`.
# Your plain `pi` and ~/.pi/agent are left completely untouched.
# Requires pi on PATH (https://github.com/earendil-works/pi).
set -euo pipefail

repo="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
dir="${PICOPI_HOME:-${XDG_CONFIG_HOME:-$HOME/.config}/picopi}"
bindir="${PICOPI_BINDIR:-$HOME/.local/bin}"

pi_bin="$(command -v pi || true)"
if [ -z "$pi_bin" ]; then
  echo "error: 'pi' not found on PATH. Install it first:" >&2
  echo "  https://github.com/earendil-works/pi" >&2
  exit 1
fi

echo "Installing picopi launcher; config dir: $dir"
mkdir -p "$dir"

# One-time migration off the old "copy source into the config dir" layout.
if [ -e "$dir/.stamp" ] || [ -d "$dir/src" ]; then
  echo "  migrating: removing old in-config source copies"
  rm -rf "$dir/.stamp" "$dir/src" "$dir/agents" "$dir/prompts" "$dir/themes" "$dir/AGENTS.md"
  if command -v python3 >/dev/null && [ -e "$dir/settings.json" ]; then
    python3 - "$dir/settings.json" <<'PY'
import json, sys
p = sys.argv[1]
s = json.load(open(p))
for k in ("extensions", "prompts", "themes", "skills"):
    s.pop(k, None)
json.dump(s, open(p, "w"), indent=2)
PY
    echo "  migrating: stripped resource-wiring keys from settings.json"
  fi
fi

# Seed user-owned files once; never clobber.
if [ -e "$dir/config.json" ]; then
  echo "  kept    config.json"
else
  cp "$repo/agent/config.json" "$dir/config.json"
  echo "  created config.json"
fi
if [ -e "$dir/settings.json" ]; then
  echo "  kept    settings.json"
else
  cp "$repo/agent/settings.json" "$dir/settings.json"
  echo "  created settings.json"
fi
[ -e "$dir/models.json" ] || printf '{\n  "providers": {}\n}\n' > "$dir/models.json"

# `picopi` launcher: points pi at the config dir and loads all source from the
# repo via CLI flags. Resolves pi from PATH at runtime (baked path as fallback)
# and intercepts `picopi --update`.
mkdir -p "$bindir"
launcher="$bindir/picopi"
cat > "$launcher" <<LAUNCHER
#!/usr/bin/env bash
# picopi launcher (generated by scripts/install.sh). Runs pi against the picopi
# config dir, loading all source from the repo. Override the dir with \$PICOPI_HOME.
repo=$(printf '%q' "$repo")
if [ "\${1:-}" = "--update" ] || [ "\${1:-}" = "upgrade" ]; then exec "\$repo/scripts/update.sh" "\${@:2}"; fi
if [ "\${1:-}" = "-h" ] || [ "\${1:-}" = "--help" ]; then cat <<'PICOPIHELP'
picopi — a batteries-included pi setup (wrapper around pi)

Usage:
  picopi [pi options...]      launch picopi (all options forwarded to pi)
  picopi --update             update picopi + pi
  picopi --update --no-pi     update picopi only
  picopi upgrade              alias for --update
  picopi -h, --help           show this help

In-app slash commands: /picopi, /preset, /undo, /todos, /review, /research (more in README).
Config dir: \$PICOPI_HOME (default ~/.config/picopi).
For pi's own options, run: pi --help
PICOPIHELP
exit 0; fi
pi_bin="\$(command -v pi || true)"
[ -n "\$pi_bin" ] || pi_bin=$(printf '%q' "$pi_bin")
exec env PI_CODING_AGENT_DIR="\${PICOPI_HOME:-$dir}" "\$pi_bin" \\
  --extension "\$repo/src" \\
  --prompt-template "\$repo/agent/prompts" \\
  --theme "\$repo/agent/themes" \\
  --append-system-prompt "\$repo/agent/AGENTS.md" \\
  "\$@"
LAUNCHER
chmod +x "$launcher"
echo "  created $launcher"

in_path=no
case ":$PATH:" in *":$bindir:"*) in_path=yes ;; esac

cat <<EOF

Your config lives in: $dir/
  config.json    picopi roles/aliases — map pro/flash to models you can use
  models.json    custom providers/gateways only (built-ins just need /login)
  settings.json  pi settings
picopi source stays in the repo: $repo (update with 'git pull')

Run it with:  picopi
EOF

if [ "$in_path" = no ]; then
  cat <<EOF

Note: $bindir is not on your PATH. Add it (then restart your shell):
  export PATH="$bindir:\$PATH"
Or run directly: $launcher
EOF
fi

cat <<EOF

Then run 'picopi' and use /login to authenticate a provider (OAuth or API key;
see pi's provider docs). Built-in providers need no models.json.

Uninstall: rm $launcher && rm -rf $dir
EOF
